// Mocks generated by Mockito 5.4.4 from annotations
// in opensocialapp/test/features/chat/presentation/bloc/chat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i12;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:opensocialapp/core/errors/failures.dart' as _i6;
import 'package:opensocialapp/core/services/socket_service.dart' as _i11;
import 'package:opensocialapp/features/chat/domain/entities/conversation_entity.dart'
    as _i7;
import 'package:opensocialapp/features/chat/domain/entities/message_entity.dart'
    as _i9;
import 'package:opensocialapp/features/chat/domain/repositories/chat_repository.dart'
    as _i2;
import 'package:opensocialapp/features/chat/domain/usecases/load_conversations_usecase.dart'
    as _i4;
import 'package:opensocialapp/features/chat/domain/usecases/load_messages_usecase.dart'
    as _i8;
import 'package:opensocialapp/features/chat/domain/usecases/send_message_usecase.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatRepository_0 extends _i1.SmartFake
    implements _i2.ChatRepository {
  _FakeChatRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoadConversationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadConversationsUseCase extends _i1.Mock
    implements _i4.LoadConversationsUseCase {
  MockLoadConversationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeChatRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ChatRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.ConversationEntity>>> call(
          _i4.LoadConversationsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, List<_i7.ConversationEntity>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.ConversationEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.ConversationEntity>>>);
}

/// A class which mocks [LoadMessagesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadMessagesUseCase extends _i1.Mock
    implements _i8.LoadMessagesUseCase {
  MockLoadMessagesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeChatRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ChatRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.MessageEntity>>> call(
          _i2.LoadMessagesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i9.MessageEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i9.MessageEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i9.MessageEntity>>>);
}

/// A class which mocks [SendMessageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendMessageUseCase extends _i1.Mock
    implements _i10.SendMessageUseCase {
  MockSendMessageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeChatRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ChatRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i9.MessageEntity>> call(
          _i10.SendMessageUseCaseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i9.MessageEntity>>.value(
                _FakeEither_1<_i6.Failure, _i9.MessageEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i9.MessageEntity>>);
}

/// A class which mocks [SocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocketService extends _i1.Mock implements _i11.SocketService {
  MockSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.SocketStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i11.SocketStatus.disconnected,
      ) as _i11.SocketStatus);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<Map<String, dynamic>> get messageStream => (super.noSuchMethod(
        Invocation.getter(#messageStream),
        returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
      ) as _i5.Stream<Map<String, dynamic>>);

  @override
  _i5.Stream<Map<String, dynamic>> get typingStream => (super.noSuchMethod(
        Invocation.getter(#typingStream),
        returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
      ) as _i5.Stream<Map<String, dynamic>>);

  @override
  _i5.Stream<Map<String, dynamic>> get readReceiptStream => (super.noSuchMethod(
        Invocation.getter(#readReceiptStream),
        returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
      ) as _i5.Stream<Map<String, dynamic>>);

  @override
  _i5.Stream<Map<String, dynamic>> get callStream => (super.noSuchMethod(
        Invocation.getter(#callStream),
        returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
      ) as _i5.Stream<Map<String, dynamic>>);

  @override
  _i5.Stream<Map<String, dynamic>> get presenceStream => (super.noSuchMethod(
        Invocation.getter(#presenceStream),
        returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
      ) as _i5.Stream<Map<String, dynamic>>);

  @override
  _i5.Stream<_i11.SocketStatus> get connectionStream => (super.noSuchMethod(
        Invocation.getter(#connectionStream),
        returnValue: _i5.Stream<_i11.SocketStatus>.empty(),
      ) as _i5.Stream<_i11.SocketStatus>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void connect(String? userId) => super.noSuchMethod(
        Invocation.method(
          #connect,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void joinConversation(String? conversationId) => super.noSuchMethod(
        Invocation.method(
          #joinConversation,
          [conversationId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void leaveConversation(String? conversationId) => super.noSuchMethod(
        Invocation.method(
          #leaveConversation,
          [conversationId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendMessage({
    required String? conversationId,
    required Map<String, dynamic>? message,
    required List<String>? participantIds,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #conversationId: conversationId,
            #message: message,
            #participantIds: participantIds,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendTyping(
    String? conversationId,
    bool? isTyping,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #sendTyping,
          [
            conversationId,
            isTyping,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendReadReceipt(
    String? conversationId,
    List<String>? messageIds,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #sendReadReceipt,
          [
            conversationId,
            messageIds,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendDeliveryConfirmation(
    String? conversationId,
    List<String>? messageIds,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #sendDeliveryConfirmation,
          [
            conversationId,
            messageIds,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendCallOffer({
    required String? callId,
    required String? calleeId,
    required String? callerName,
    String? callerAvatar,
    required String? callType,
    required String? sdp,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendCallOffer,
          [],
          {
            #callId: callId,
            #calleeId: calleeId,
            #callerName: callerName,
            #callerAvatar: callerAvatar,
            #callType: callType,
            #sdp: sdp,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendCallAnswer({
    required String? callId,
    required String? callerId,
    required String? sdp,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendCallAnswer,
          [],
          {
            #callId: callId,
            #callerId: callerId,
            #sdp: sdp,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendIceCandidate({
    required String? callId,
    required String? targetUserId,
    required String? candidate,
    String? sdpMid,
    int? sdpMLineIndex,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendIceCandidate,
          [],
          {
            #callId: callId,
            #targetUserId: targetUserId,
            #candidate: candidate,
            #sdpMid: sdpMid,
            #sdpMLineIndex: sdpMLineIndex,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void rejectCall(
    String? callId,
    String? callerId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #rejectCall,
          [
            callId,
            callerId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void endCall(
    String? callId,
    String? targetUserId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #endCall,
          [
            callId,
            targetUserId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendBusySignal(
    String? callId,
    String? callerId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #sendBusySignal,
          [
            callId,
            callerId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePresence(String? status) => super.noSuchMethod(
        Invocation.method(
          #updatePresence,
          [status],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void getOnlineUsers(List<String>? userIds) => super.noSuchMethod(
        Invocation.method(
          #getOnlineUsers,
          [userIds],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disconnect() => super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
