// Mocks generated by Mockito 5.4.4 from annotations
// in opensocialapp/test/features/auth/domain/usecases/login_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:opensocialapp/core/errors/failures.dart' as _i5;
import 'package:opensocialapp/features/auth/domain/entities/user_entity.dart'
    as _i6;
import 'package:opensocialapp/features/auth/domain/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.AuthResult>> login(
          _i3.LoginParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i3.AuthResult>>.value(
            _FakeEither_0<_i5.Failure, _i3.AuthResult>(
          this,
          Invocation.method(
            #login,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i3.AuthResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.AuthResult>> register(
          _i3.RegisterParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i3.AuthResult>>.value(
            _FakeEither_0<_i5.Failure, _i3.AuthResult>(
          this,
          Invocation.method(
            #register,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i3.AuthResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.AuthResult?>> checkAuth() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAuth,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i3.AuthResult?>>.value(
            _FakeEither_0<_i5.Failure, _i3.AuthResult?>(
          this,
          Invocation.method(
            #checkAuth,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i3.AuthResult?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>> updateProfile({
    String? fullName,
    String? profileUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #fullName: fullName,
            #profileUrl: profileUrl,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.UserEntity>(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #fullName: fullName,
              #profileUrl: profileUrl,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>);
}
